// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.2
// source: encryptionkeyrotation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EncKeyRotateRequest contains the information needed to identify
// the volume by the SP and access any backend services so that the key can be
// rotated.
type EncKeyRotateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the pv
	// This field is required
	PvName string `protobuf:"bytes,1,opt,name=pv_name,json=pvName,proto3" json:"pv_name,omitempty"`
}

func (x *EncKeyRotateRequest) Reset() {
	*x = EncKeyRotateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encryptionkeyrotation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncKeyRotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncKeyRotateRequest) ProtoMessage() {}

func (x *EncKeyRotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryptionkeyrotation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncKeyRotateRequest.ProtoReflect.Descriptor instead.
func (*EncKeyRotateRequest) Descriptor() ([]byte, []int) {
	return file_encryptionkeyrotation_proto_rawDescGZIP(), []int{0}
}

func (x *EncKeyRotateRequest) GetPvName() string {
	if x != nil {
		return x.PvName
	}
	return ""
}

// EncKeyRotateResponse holds the information about the result of the
// EncKeyRotateRequest call.
type EncKeyRotateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EncKeyRotateResponse) Reset() {
	*x = EncKeyRotateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encryptionkeyrotation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncKeyRotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncKeyRotateResponse) ProtoMessage() {}

func (x *EncKeyRotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryptionkeyrotation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncKeyRotateResponse.ProtoReflect.Descriptor instead.
func (*EncKeyRotateResponse) Descriptor() ([]byte, []int) {
	return file_encryptionkeyrotation_proto_rawDescGZIP(), []int{1}
}

var File_encryptionkeyrotation_proto protoreflect.FileDescriptor

var file_encryptionkeyrotation_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x6b, 0x65, 0x79, 0x72,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x6b, 0x65, 0x79, 0x72, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x13, 0x45, 0x6e, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x6f,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x76, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x76,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x45, 0x6e, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x6f,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x7b, 0x0a, 0x0e,
	0x45, 0x6e, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x69,
	0x0a, 0x0c, 0x45, 0x6e, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a,
	0x2e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x6b, 0x65, 0x79, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x6f, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x6b, 0x65, 0x79, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x73, 0x69, 0x2d, 0x61, 0x64, 0x64, 0x6f,
	0x6e, 0x73, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2d, 0x63, 0x73,
	0x69, 0x2d, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encryptionkeyrotation_proto_rawDescOnce sync.Once
	file_encryptionkeyrotation_proto_rawDescData = file_encryptionkeyrotation_proto_rawDesc
)

func file_encryptionkeyrotation_proto_rawDescGZIP() []byte {
	file_encryptionkeyrotation_proto_rawDescOnce.Do(func() {
		file_encryptionkeyrotation_proto_rawDescData = protoimpl.X.CompressGZIP(file_encryptionkeyrotation_proto_rawDescData)
	})
	return file_encryptionkeyrotation_proto_rawDescData
}

var file_encryptionkeyrotation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_encryptionkeyrotation_proto_goTypes = []any{
	(*EncKeyRotateRequest)(nil),  // 0: encryptionkeyrotation.EncKeyRotateRequest
	(*EncKeyRotateResponse)(nil), // 1: encryptionkeyrotation.EncKeyRotateResponse
}
var file_encryptionkeyrotation_proto_depIdxs = []int32{
	0, // 0: encryptionkeyrotation.EncKeyRotation.EncKeyRotate:input_type -> encryptionkeyrotation.EncKeyRotateRequest
	1, // 1: encryptionkeyrotation.EncKeyRotation.EncKeyRotate:output_type -> encryptionkeyrotation.EncKeyRotateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_encryptionkeyrotation_proto_init() }
func file_encryptionkeyrotation_proto_init() {
	if File_encryptionkeyrotation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encryptionkeyrotation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EncKeyRotateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encryptionkeyrotation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EncKeyRotateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encryptionkeyrotation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encryptionkeyrotation_proto_goTypes,
		DependencyIndexes: file_encryptionkeyrotation_proto_depIdxs,
		MessageInfos:      file_encryptionkeyrotation_proto_msgTypes,
	}.Build()
	File_encryptionkeyrotation_proto = out.File
	file_encryptionkeyrotation_proto_rawDesc = nil
	file_encryptionkeyrotation_proto_goTypes = nil
	file_encryptionkeyrotation_proto_depIdxs = nil
}
