// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: encryptionkeyrotation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EncryptionKeyRotateRequest contains the information needed to identify
// the volume by the csi-addons sidecar and access any backend services so that the
// key can be rotated.
type EncryptionKeyRotateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the pv
	// This field is required
	PvName        string `protobuf:"bytes,1,opt,name=pv_name,json=pvName,proto3" json:"pv_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptionKeyRotateRequest) Reset() {
	*x = EncryptionKeyRotateRequest{}
	mi := &file_encryptionkeyrotation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionKeyRotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionKeyRotateRequest) ProtoMessage() {}

func (x *EncryptionKeyRotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryptionkeyrotation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionKeyRotateRequest.ProtoReflect.Descriptor instead.
func (*EncryptionKeyRotateRequest) Descriptor() ([]byte, []int) {
	return file_encryptionkeyrotation_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptionKeyRotateRequest) GetPvName() string {
	if x != nil {
		return x.PvName
	}
	return ""
}

// EncryptionKeyRotateResponse holds the information about the result of the
// EncryptionKeyRotateRequest call.
type EncryptionKeyRotateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptionKeyRotateResponse) Reset() {
	*x = EncryptionKeyRotateResponse{}
	mi := &file_encryptionkeyrotation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionKeyRotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionKeyRotateResponse) ProtoMessage() {}

func (x *EncryptionKeyRotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryptionkeyrotation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionKeyRotateResponse.ProtoReflect.Descriptor instead.
func (*EncryptionKeyRotateResponse) Descriptor() ([]byte, []int) {
	return file_encryptionkeyrotation_proto_rawDescGZIP(), []int{1}
}

var File_encryptionkeyrotation_proto protoreflect.FileDescriptor

const file_encryptionkeyrotation_proto_rawDesc = "" +
	"\n" +
	"\x1bencryptionkeyrotation.proto\x12\x05proto\"5\n" +
	"\x1aEncryptionKeyRotateRequest\x12\x17\n" +
	"\apv_name\x18\x01 \x01(\tR\x06pvName\"\x1d\n" +
	"\x1bEncryptionKeyRotateResponse2w\n" +
	"\x15EncryptionKeyRotation\x12^\n" +
	"\x13EncryptionKeyRotate\x12!.proto.EncryptionKeyRotateRequest\x1a\".proto.EncryptionKeyRotateResponse\"\x00B<Z:github.com/csi-addons/kubernetes-csi-addons/internal/protob\x06proto3"

var (
	file_encryptionkeyrotation_proto_rawDescOnce sync.Once
	file_encryptionkeyrotation_proto_rawDescData []byte
)

func file_encryptionkeyrotation_proto_rawDescGZIP() []byte {
	file_encryptionkeyrotation_proto_rawDescOnce.Do(func() {
		file_encryptionkeyrotation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encryptionkeyrotation_proto_rawDesc), len(file_encryptionkeyrotation_proto_rawDesc)))
	})
	return file_encryptionkeyrotation_proto_rawDescData
}

var file_encryptionkeyrotation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_encryptionkeyrotation_proto_goTypes = []any{
	(*EncryptionKeyRotateRequest)(nil),  // 0: proto.EncryptionKeyRotateRequest
	(*EncryptionKeyRotateResponse)(nil), // 1: proto.EncryptionKeyRotateResponse
}
var file_encryptionkeyrotation_proto_depIdxs = []int32{
	0, // 0: proto.EncryptionKeyRotation.EncryptionKeyRotate:input_type -> proto.EncryptionKeyRotateRequest
	1, // 1: proto.EncryptionKeyRotation.EncryptionKeyRotate:output_type -> proto.EncryptionKeyRotateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_encryptionkeyrotation_proto_init() }
func file_encryptionkeyrotation_proto_init() {
	if File_encryptionkeyrotation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encryptionkeyrotation_proto_rawDesc), len(file_encryptionkeyrotation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encryptionkeyrotation_proto_goTypes,
		DependencyIndexes: file_encryptionkeyrotation_proto_depIdxs,
		MessageInfos:      file_encryptionkeyrotation_proto_msgTypes,
	}.Build()
	File_encryptionkeyrotation_proto = out.File
	file_encryptionkeyrotation_proto_goTypes = nil
	file_encryptionkeyrotation_proto_depIdxs = nil
}
