// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.20.2
// source: encryptionkeyrotation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EncKeyRotation_EncKeyRotate_FullMethodName = "/encryptionkeyrotation.EncKeyRotation/EncKeyRotate"
)

// EncKeyRotationClient is the client API for EncKeyRotation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EncKeyRotation holds the RPC method for running
// key rotation operation on the volume.
type EncKeyRotationClient interface {
	EncKeyRotate(ctx context.Context, in *EncKeyRotateRequest, opts ...grpc.CallOption) (*EncKeyRotateResponse, error)
}

type encKeyRotationClient struct {
	cc grpc.ClientConnInterface
}

func NewEncKeyRotationClient(cc grpc.ClientConnInterface) EncKeyRotationClient {
	return &encKeyRotationClient{cc}
}

func (c *encKeyRotationClient) EncKeyRotate(ctx context.Context, in *EncKeyRotateRequest, opts ...grpc.CallOption) (*EncKeyRotateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncKeyRotateResponse)
	err := c.cc.Invoke(ctx, EncKeyRotation_EncKeyRotate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncKeyRotationServer is the server API for EncKeyRotation service.
// All implementations must embed UnimplementedEncKeyRotationServer
// for forward compatibility
//
// EncKeyRotation holds the RPC method for running
// key rotation operation on the volume.
type EncKeyRotationServer interface {
	EncKeyRotate(context.Context, *EncKeyRotateRequest) (*EncKeyRotateResponse, error)
	mustEmbedUnimplementedEncKeyRotationServer()
}

// UnimplementedEncKeyRotationServer must be embedded to have forward compatible implementations.
type UnimplementedEncKeyRotationServer struct {
}

func (UnimplementedEncKeyRotationServer) EncKeyRotate(context.Context, *EncKeyRotateRequest) (*EncKeyRotateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncKeyRotate not implemented")
}
func (UnimplementedEncKeyRotationServer) mustEmbedUnimplementedEncKeyRotationServer() {}

// UnsafeEncKeyRotationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncKeyRotationServer will
// result in compilation errors.
type UnsafeEncKeyRotationServer interface {
	mustEmbedUnimplementedEncKeyRotationServer()
}

func RegisterEncKeyRotationServer(s grpc.ServiceRegistrar, srv EncKeyRotationServer) {
	s.RegisterService(&EncKeyRotation_ServiceDesc, srv)
}

func _EncKeyRotation_EncKeyRotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncKeyRotateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncKeyRotationServer).EncKeyRotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncKeyRotation_EncKeyRotate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncKeyRotationServer).EncKeyRotate(ctx, req.(*EncKeyRotateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EncKeyRotation_ServiceDesc is the grpc.ServiceDesc for EncKeyRotation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EncKeyRotation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "encryptionkeyrotation.EncKeyRotation",
	HandlerType: (*EncKeyRotationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncKeyRotate",
			Handler:    _EncKeyRotation_EncKeyRotate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "encryptionkeyrotation.proto",
}
