// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: networkfence.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NetworkFenceRequest holds the required information to fence/unfence
// the cluster network.
type NetworkFenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin specific parameters passed in as opaque key-value pairs.
	Parameters map[string]string `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secrets required by the driver to complete the request.
	SecretName      string `protobuf:"bytes,2,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,3,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	// list of CIDR blocks on which the fencing/unfencing operation is expected
	// to be performed.
	Cidrs         []string `protobuf:"bytes,4,rep,name=cidrs,proto3" json:"cidrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkFenceRequest) Reset() {
	*x = NetworkFenceRequest{}
	mi := &file_networkfence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkFenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkFenceRequest) ProtoMessage() {}

func (x *NetworkFenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkfence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkFenceRequest.ProtoReflect.Descriptor instead.
func (*NetworkFenceRequest) Descriptor() ([]byte, []int) {
	return file_networkfence_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkFenceRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *NetworkFenceRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *NetworkFenceRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

func (x *NetworkFenceRequest) GetCidrs() []string {
	if x != nil {
		return x.Cidrs
	}
	return nil
}

// NetworkFenceResponse is returned by the CSI-driver as a result of
// the FenceRequest call.
type NetworkFenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkFenceResponse) Reset() {
	*x = NetworkFenceResponse{}
	mi := &file_networkfence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkFenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkFenceResponse) ProtoMessage() {}

func (x *NetworkFenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networkfence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkFenceResponse.ProtoReflect.Descriptor instead.
func (*NetworkFenceResponse) Descriptor() ([]byte, []int) {
	return file_networkfence_proto_rawDescGZIP(), []int{1}
}

// FenceClientsRequest contains the necessary information to identify
// the clients that need fencing.
type FenceClientsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin-specific parameters passed in as opaque key-value pairs.
	Parameters map[string]string `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secrets required by the driver to complete the request.
	SecretName      string `protobuf:"bytes,2,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,3,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FenceClientsRequest) Reset() {
	*x = FenceClientsRequest{}
	mi := &file_networkfence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceClientsRequest) ProtoMessage() {}

func (x *FenceClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkfence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceClientsRequest.ProtoReflect.Descriptor instead.
func (*FenceClientsRequest) Descriptor() ([]byte, []int) {
	return file_networkfence_proto_rawDescGZIP(), []int{2}
}

func (x *FenceClientsRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *FenceClientsRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *FenceClientsRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

// FenceClientsResponse holds the information about clients that require
// fencing.
type FenceClientsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of clients that need to be fenced.
	Clients       []*ClientDetails `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FenceClientsResponse) Reset() {
	*x = FenceClientsResponse{}
	mi := &file_networkfence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceClientsResponse) ProtoMessage() {}

func (x *FenceClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networkfence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceClientsResponse.ProtoReflect.Descriptor instead.
func (*FenceClientsResponse) Descriptor() ([]byte, []int) {
	return file_networkfence_proto_rawDescGZIP(), []int{3}
}

func (x *FenceClientsResponse) GetClients() []*ClientDetails {
	if x != nil {
		return x.Clients
	}
	return nil
}

// ClientDetails holds the information about the client that requires fencing.
type ClientDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id represents the unique identifier of the client.
	// Required field.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// list of cidrs that represent the client's local cidrs.
	// Required field.
	Cidrs         []string `protobuf:"bytes,2,rep,name=cidrs,proto3" json:"cidrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDetails) Reset() {
	*x = ClientDetails{}
	mi := &file_networkfence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDetails) ProtoMessage() {}

func (x *ClientDetails) ProtoReflect() protoreflect.Message {
	mi := &file_networkfence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDetails.ProtoReflect.Descriptor instead.
func (*ClientDetails) Descriptor() ([]byte, []int) {
	return file_networkfence_proto_rawDescGZIP(), []int{4}
}

func (x *ClientDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientDetails) GetCidrs() []string {
	if x != nil {
		return x.Cidrs
	}
	return nil
}

var File_networkfence_proto protoreflect.FileDescriptor

const file_networkfence_proto_rawDesc = "" +
	"\n" +
	"\x12networkfence.proto\x12\x05proto\"\x82\x02\n" +
	"\x13NetworkFenceRequest\x12J\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2*.proto.NetworkFenceRequest.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vsecret_name\x18\x02 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x03 \x01(\tR\x0fsecretNamespace\x12\x14\n" +
	"\x05cidrs\x18\x04 \x03(\tR\x05cidrs\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14NetworkFenceResponse\"\xec\x01\n" +
	"\x13FenceClientsRequest\x12J\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2*.proto.FenceClientsRequest.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vsecret_name\x18\x02 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x03 \x01(\tR\x0fsecretNamespace\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x14FenceClientsResponse\x12.\n" +
	"\aclients\x18\x01 \x03(\v2\x14.proto.ClientDetailsR\aclients\"5\n" +
	"\rClientDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05cidrs\x18\x02 \x03(\tR\x05cidrs2\x82\x02\n" +
	"\fNetworkFence\x12P\n" +
	"\x13FenceClusterNetwork\x12\x1a.proto.NetworkFenceRequest\x1a\x1b.proto.NetworkFenceResponse\"\x00\x12R\n" +
	"\x15UnFenceClusterNetwork\x12\x1a.proto.NetworkFenceRequest\x1a\x1b.proto.NetworkFenceResponse\"\x00\x12L\n" +
	"\x0fGetFenceClients\x12\x1a.proto.FenceClientsRequest\x1a\x1b.proto.FenceClientsResponse\"\x00B<Z:github.com/csi-addons/kubernetes-csi-addons/internal/protob\x06proto3"

var (
	file_networkfence_proto_rawDescOnce sync.Once
	file_networkfence_proto_rawDescData []byte
)

func file_networkfence_proto_rawDescGZIP() []byte {
	file_networkfence_proto_rawDescOnce.Do(func() {
		file_networkfence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networkfence_proto_rawDesc), len(file_networkfence_proto_rawDesc)))
	})
	return file_networkfence_proto_rawDescData
}

var file_networkfence_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_networkfence_proto_goTypes = []any{
	(*NetworkFenceRequest)(nil),  // 0: proto.NetworkFenceRequest
	(*NetworkFenceResponse)(nil), // 1: proto.NetworkFenceResponse
	(*FenceClientsRequest)(nil),  // 2: proto.FenceClientsRequest
	(*FenceClientsResponse)(nil), // 3: proto.FenceClientsResponse
	(*ClientDetails)(nil),        // 4: proto.ClientDetails
	nil,                          // 5: proto.NetworkFenceRequest.ParametersEntry
	nil,                          // 6: proto.FenceClientsRequest.ParametersEntry
}
var file_networkfence_proto_depIdxs = []int32{
	5, // 0: proto.NetworkFenceRequest.parameters:type_name -> proto.NetworkFenceRequest.ParametersEntry
	6, // 1: proto.FenceClientsRequest.parameters:type_name -> proto.FenceClientsRequest.ParametersEntry
	4, // 2: proto.FenceClientsResponse.clients:type_name -> proto.ClientDetails
	0, // 3: proto.NetworkFence.FenceClusterNetwork:input_type -> proto.NetworkFenceRequest
	0, // 4: proto.NetworkFence.UnFenceClusterNetwork:input_type -> proto.NetworkFenceRequest
	2, // 5: proto.NetworkFence.GetFenceClients:input_type -> proto.FenceClientsRequest
	1, // 6: proto.NetworkFence.FenceClusterNetwork:output_type -> proto.NetworkFenceResponse
	1, // 7: proto.NetworkFence.UnFenceClusterNetwork:output_type -> proto.NetworkFenceResponse
	3, // 8: proto.NetworkFence.GetFenceClients:output_type -> proto.FenceClientsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_networkfence_proto_init() }
func file_networkfence_proto_init() {
	if File_networkfence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networkfence_proto_rawDesc), len(file_networkfence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_networkfence_proto_goTypes,
		DependencyIndexes: file_networkfence_proto_depIdxs,
		MessageInfos:      file_networkfence_proto_msgTypes,
	}.Build()
	File_networkfence_proto = out.File
	file_networkfence_proto_goTypes = nil
	file_networkfence_proto_depIdxs = nil
}
