// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: reclaimspace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReclaimSpaceRequest contains the information i.e., pv_name
// received from the CSIAddons controller for performing the reclaim operation.
type ReclaimSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the pv. This field is REQUIRED.
	PvName        string `protobuf:"bytes,1,opt,name=pv_name,json=pvName,proto3" json:"pv_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReclaimSpaceRequest) Reset() {
	*x = ReclaimSpaceRequest{}
	mi := &file_reclaimspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReclaimSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReclaimSpaceRequest) ProtoMessage() {}

func (x *ReclaimSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reclaimspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReclaimSpaceRequest.ProtoReflect.Descriptor instead.
func (*ReclaimSpaceRequest) Descriptor() ([]byte, []int) {
	return file_reclaimspace_proto_rawDescGZIP(), []int{0}
}

func (x *ReclaimSpaceRequest) GetPvName() string {
	if x != nil {
		return x.PvName
	}
	return ""
}

// ReclaimSpaceResponse holds the information about the result of the
// ControllerReclaimSpaceRequest/NodeReclaimSpaceRequest call.
type ReclaimSpaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is OPTIONAL. This allows the SP to inform the CO about the
	// storage consumption before the ReclaimSpace operation was executed.
	PreUsage *StorageConsumption `protobuf:"bytes,1,opt,name=pre_usage,json=preUsage,proto3" json:"pre_usage,omitempty"`
	// This field is OPTIONAL. This allows the SP to inform the CO about the
	// storage consumption after the ReclaimSpace operation was executed.
	PostUsage     *StorageConsumption `protobuf:"bytes,2,opt,name=post_usage,json=postUsage,proto3" json:"post_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReclaimSpaceResponse) Reset() {
	*x = ReclaimSpaceResponse{}
	mi := &file_reclaimspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReclaimSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReclaimSpaceResponse) ProtoMessage() {}

func (x *ReclaimSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reclaimspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReclaimSpaceResponse.ProtoReflect.Descriptor instead.
func (*ReclaimSpaceResponse) Descriptor() ([]byte, []int) {
	return file_reclaimspace_proto_rawDescGZIP(), []int{1}
}

func (x *ReclaimSpaceResponse) GetPreUsage() *StorageConsumption {
	if x != nil {
		return x.PreUsage
	}
	return nil
}

func (x *ReclaimSpaceResponse) GetPostUsage() *StorageConsumption {
	if x != nil {
		return x.PostUsage
	}
	return nil
}

// StorageConsumption contains the usage in bytes.
type StorageConsumption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED. usage_bytes contains the consumed storage in
	// bytes.
	UsageBytes    int64 `protobuf:"varint,1,opt,name=usage_bytes,json=usageBytes,proto3" json:"usage_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageConsumption) Reset() {
	*x = StorageConsumption{}
	mi := &file_reclaimspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConsumption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConsumption) ProtoMessage() {}

func (x *StorageConsumption) ProtoReflect() protoreflect.Message {
	mi := &file_reclaimspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConsumption.ProtoReflect.Descriptor instead.
func (*StorageConsumption) Descriptor() ([]byte, []int) {
	return file_reclaimspace_proto_rawDescGZIP(), []int{2}
}

func (x *StorageConsumption) GetUsageBytes() int64 {
	if x != nil {
		return x.UsageBytes
	}
	return 0
}

var File_reclaimspace_proto protoreflect.FileDescriptor

const file_reclaimspace_proto_rawDesc = "" +
	"\n" +
	"\x12reclaimspace.proto\x12\x05proto\".\n" +
	"\x13ReclaimSpaceRequest\x12\x17\n" +
	"\apv_name\x18\x01 \x01(\tR\x06pvName\"\x88\x01\n" +
	"\x14ReclaimSpaceResponse\x126\n" +
	"\tpre_usage\x18\x01 \x01(\v2\x19.proto.StorageConsumptionR\bpreUsage\x128\n" +
	"\n" +
	"post_usage\x18\x02 \x01(\v2\x19.proto.StorageConsumptionR\tpostUsage\"5\n" +
	"\x12StorageConsumption\x12\x1f\n" +
	"\vusage_bytes\x18\x01 \x01(\x03R\n" +
	"usageBytes2\xb2\x01\n" +
	"\fReclaimSpace\x12S\n" +
	"\x16ControllerReclaimSpace\x12\x1a.proto.ReclaimSpaceRequest\x1a\x1b.proto.ReclaimSpaceResponse\"\x00\x12M\n" +
	"\x10NodeReclaimSpace\x12\x1a.proto.ReclaimSpaceRequest\x1a\x1b.proto.ReclaimSpaceResponse\"\x00B<Z:github.com/csi-addons/kubernetes-csi-addons/internal/protob\x06proto3"

var (
	file_reclaimspace_proto_rawDescOnce sync.Once
	file_reclaimspace_proto_rawDescData []byte
)

func file_reclaimspace_proto_rawDescGZIP() []byte {
	file_reclaimspace_proto_rawDescOnce.Do(func() {
		file_reclaimspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reclaimspace_proto_rawDesc), len(file_reclaimspace_proto_rawDesc)))
	})
	return file_reclaimspace_proto_rawDescData
}

var file_reclaimspace_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_reclaimspace_proto_goTypes = []any{
	(*ReclaimSpaceRequest)(nil),  // 0: proto.ReclaimSpaceRequest
	(*ReclaimSpaceResponse)(nil), // 1: proto.ReclaimSpaceResponse
	(*StorageConsumption)(nil),   // 2: proto.StorageConsumption
}
var file_reclaimspace_proto_depIdxs = []int32{
	2, // 0: proto.ReclaimSpaceResponse.pre_usage:type_name -> proto.StorageConsumption
	2, // 1: proto.ReclaimSpaceResponse.post_usage:type_name -> proto.StorageConsumption
	0, // 2: proto.ReclaimSpace.ControllerReclaimSpace:input_type -> proto.ReclaimSpaceRequest
	0, // 3: proto.ReclaimSpace.NodeReclaimSpace:input_type -> proto.ReclaimSpaceRequest
	1, // 4: proto.ReclaimSpace.ControllerReclaimSpace:output_type -> proto.ReclaimSpaceResponse
	1, // 5: proto.ReclaimSpace.NodeReclaimSpace:output_type -> proto.ReclaimSpaceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reclaimspace_proto_init() }
func file_reclaimspace_proto_init() {
	if File_reclaimspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reclaimspace_proto_rawDesc), len(file_reclaimspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reclaimspace_proto_goTypes,
		DependencyIndexes: file_reclaimspace_proto_depIdxs,
		MessageInfos:      file_reclaimspace_proto_msgTypes,
	}.Build()
	File_reclaimspace_proto = out.File
	file_reclaimspace_proto_goTypes = nil
	file_reclaimspace_proto_depIdxs = nil
}
