// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: replication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the type of replication status that can be returned
// by a storage vendor.
type GetVolumeReplicationInfoResponse_Status int32

const (
	// UNKNOWN indicates that the SP does not know the current
	// replication status.
	GetVolumeReplicationInfoResponse_UNKNOWN GetVolumeReplicationInfoResponse_Status = 0
	// HEALTHY indicates that the replication is working properly.
	GetVolumeReplicationInfoResponse_HEALTHY GetVolumeReplicationInfoResponse_Status = 1
	// DEGRADED indicates that the replication has stopped working
	// and it may require user intervention.
	GetVolumeReplicationInfoResponse_DEGRADED GetVolumeReplicationInfoResponse_Status = 2
	// ERROR indicates that there is an error in replication
	// and it may require user intervention.
	GetVolumeReplicationInfoResponse_ERROR GetVolumeReplicationInfoResponse_Status = 3
)

// Enum value maps for GetVolumeReplicationInfoResponse_Status.
var (
	GetVolumeReplicationInfoResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "DEGRADED",
		3: "ERROR",
	}
	GetVolumeReplicationInfoResponse_Status_value = map[string]int32{
		"UNKNOWN":  0,
		"HEALTHY":  1,
		"DEGRADED": 2,
		"ERROR":    3,
	}
)

func (x GetVolumeReplicationInfoResponse_Status) Enum() *GetVolumeReplicationInfoResponse_Status {
	p := new(GetVolumeReplicationInfoResponse_Status)
	*p = x
	return p
}

func (x GetVolumeReplicationInfoResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetVolumeReplicationInfoResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_replication_proto_enumTypes[0].Descriptor()
}

func (GetVolumeReplicationInfoResponse_Status) Type() protoreflect.EnumType {
	return &file_replication_proto_enumTypes[0]
}

func (x GetVolumeReplicationInfoResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetVolumeReplicationInfoResponse_Status.Descriptor instead.
func (GetVolumeReplicationInfoResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{11, 0}
}

// EnableVolumeReplicationRequest holds the required information to enable
// replication on a volume.
type EnableVolumeReplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for the replication.
	// This field is OPTIONAL.
	// This field MUST contain enough information, together with volume_id,
	// to uniquely identify this specific replication
	// vs all other replications supported by this plugin.
	ReplicationId string `protobuf:"bytes,2,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	// Plugin specific parameters passed in as opaque key-value pairs.
	Parameters map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secrets required by the driver to complete the request.
	SecretName      string `protobuf:"bytes,4,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,5,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	// If specified, this field will contain volume or volume group id
	// for replication.
	ReplicationSource *ReplicationSource `protobuf:"bytes,6,opt,name=replication_source,json=replicationSource,proto3" json:"replication_source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnableVolumeReplicationRequest) Reset() {
	*x = EnableVolumeReplicationRequest{}
	mi := &file_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableVolumeReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableVolumeReplicationRequest) ProtoMessage() {}

func (x *EnableVolumeReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableVolumeReplicationRequest.ProtoReflect.Descriptor instead.
func (*EnableVolumeReplicationRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{0}
}

func (x *EnableVolumeReplicationRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

func (x *EnableVolumeReplicationRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *EnableVolumeReplicationRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *EnableVolumeReplicationRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

func (x *EnableVolumeReplicationRequest) GetReplicationSource() *ReplicationSource {
	if x != nil {
		return x.ReplicationSource
	}
	return nil
}

// EnableVolumeReplicationResponse holds the information to send when
// replication is successfully enabled on a volume.
type EnableVolumeReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableVolumeReplicationResponse) Reset() {
	*x = EnableVolumeReplicationResponse{}
	mi := &file_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableVolumeReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableVolumeReplicationResponse) ProtoMessage() {}

func (x *EnableVolumeReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableVolumeReplicationResponse.ProtoReflect.Descriptor instead.
func (*EnableVolumeReplicationResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{1}
}

// DisableVolumeReplicationRequest holds the required information to disable
// replication on a volume.
type DisableVolumeReplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for the replication.
	// This field is OPTIONAL.
	// This field MUST contain enough information, together with volume_id,
	// to uniquely identify this specific replication
	// vs all other replications supported by this plugin.
	ReplicationId string `protobuf:"bytes,2,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	// Plugin specific parameters passed in as opaque key-value pairs.
	Parameters map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secrets required by the driver to complete the request.
	SecretName      string `protobuf:"bytes,4,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,5,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	// If specified, this field will contain volume or volume group id
	// for replication.
	ReplicationSource *ReplicationSource `protobuf:"bytes,6,opt,name=replication_source,json=replicationSource,proto3" json:"replication_source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DisableVolumeReplicationRequest) Reset() {
	*x = DisableVolumeReplicationRequest{}
	mi := &file_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableVolumeReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableVolumeReplicationRequest) ProtoMessage() {}

func (x *DisableVolumeReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableVolumeReplicationRequest.ProtoReflect.Descriptor instead.
func (*DisableVolumeReplicationRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{2}
}

func (x *DisableVolumeReplicationRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

func (x *DisableVolumeReplicationRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *DisableVolumeReplicationRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *DisableVolumeReplicationRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

func (x *DisableVolumeReplicationRequest) GetReplicationSource() *ReplicationSource {
	if x != nil {
		return x.ReplicationSource
	}
	return nil
}

// DisableVolumeReplicationResponse holds the information to send when
// replication is successfully disabled on a volume.
type DisableVolumeReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableVolumeReplicationResponse) Reset() {
	*x = DisableVolumeReplicationResponse{}
	mi := &file_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableVolumeReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableVolumeReplicationResponse) ProtoMessage() {}

func (x *DisableVolumeReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableVolumeReplicationResponse.ProtoReflect.Descriptor instead.
func (*DisableVolumeReplicationResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{3}
}

// PromoteVolumeRequest holds the required information to promote volume as a
// primary on local cluster.
type PromoteVolumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for the replication.
	// This field is OPTIONAL.
	// This field MUST contain enough information, together with volume_id,
	// to uniquely identify this specific replication
	// vs all other replications supported by this plugin.
	ReplicationId string `protobuf:"bytes,2,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	// This field is optional.
	// Default value is false, force option to Promote the volume.
	Force bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	// Plugin specific parameters passed in as opaque key-value pairs.
	Parameters map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secrets required by the driver to complete the request.
	SecretName      string `protobuf:"bytes,5,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,6,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	// If specified, this field will contain volume or volume group id
	// for replication.
	ReplicationSource *ReplicationSource `protobuf:"bytes,7,opt,name=replication_source,json=replicationSource,proto3" json:"replication_source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PromoteVolumeRequest) Reset() {
	*x = PromoteVolumeRequest{}
	mi := &file_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteVolumeRequest) ProtoMessage() {}

func (x *PromoteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteVolumeRequest.ProtoReflect.Descriptor instead.
func (*PromoteVolumeRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{4}
}

func (x *PromoteVolumeRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

func (x *PromoteVolumeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *PromoteVolumeRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *PromoteVolumeRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *PromoteVolumeRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

func (x *PromoteVolumeRequest) GetReplicationSource() *ReplicationSource {
	if x != nil {
		return x.ReplicationSource
	}
	return nil
}

// PromoteVolumeResponse holds the information to send when
// volume is successfully promoted.
type PromoteVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteVolumeResponse) Reset() {
	*x = PromoteVolumeResponse{}
	mi := &file_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteVolumeResponse) ProtoMessage() {}

func (x *PromoteVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteVolumeResponse.ProtoReflect.Descriptor instead.
func (*PromoteVolumeResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{5}
}

// DemoteVolumeRequest holds the required information to demote volume on local
// cluster.
type DemoteVolumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for the replication.
	// This field is OPTIONAL.
	// This field MUST contain enough information, together with volume_id,
	// to uniquely identify this specific replication
	// vs all other replications supported by this plugin.
	ReplicationId string `protobuf:"bytes,2,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	// This field is optional.
	// Default value is false, force option to Demote the volume.
	Force bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	// Plugin specific parameters passed in as opaque key-value pairs.
	Parameters map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secrets required by the driver to complete the request.
	SecretName      string `protobuf:"bytes,5,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,6,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	// If specified, this field will contain volume or volume group id
	// for replication.
	ReplicationSource *ReplicationSource `protobuf:"bytes,7,opt,name=replication_source,json=replicationSource,proto3" json:"replication_source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DemoteVolumeRequest) Reset() {
	*x = DemoteVolumeRequest{}
	mi := &file_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteVolumeRequest) ProtoMessage() {}

func (x *DemoteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteVolumeRequest.ProtoReflect.Descriptor instead.
func (*DemoteVolumeRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{6}
}

func (x *DemoteVolumeRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

func (x *DemoteVolumeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *DemoteVolumeRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *DemoteVolumeRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *DemoteVolumeRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

func (x *DemoteVolumeRequest) GetReplicationSource() *ReplicationSource {
	if x != nil {
		return x.ReplicationSource
	}
	return nil
}

// DemoteVolumeResponse holds the information to send when
// volume is successfully demoted.
type DemoteVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoteVolumeResponse) Reset() {
	*x = DemoteVolumeResponse{}
	mi := &file_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoteVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteVolumeResponse) ProtoMessage() {}

func (x *DemoteVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteVolumeResponse.ProtoReflect.Descriptor instead.
func (*DemoteVolumeResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{7}
}

// ResyncVolumeRequest holds the required information to resync volume.
type ResyncVolumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for the replication.
	// This field is OPTIONAL.
	// This field MUST contain enough information, together with volume_id,
	// to uniquely identify this specific replication
	// vs all other replications supported by this plugin.
	ReplicationId string `protobuf:"bytes,2,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	// This field is optional.
	// Default value is false, force option to Resync the volume.
	Force bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	// Plugin specific parameters passed in as opaque key-value pairs.
	Parameters map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secrets required by the driver to complete the request.
	SecretName      string `protobuf:"bytes,5,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,6,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	// If specified, this field will contain volume or volume group id
	// for replication.
	ReplicationSource *ReplicationSource `protobuf:"bytes,7,opt,name=replication_source,json=replicationSource,proto3" json:"replication_source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResyncVolumeRequest) Reset() {
	*x = ResyncVolumeRequest{}
	mi := &file_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResyncVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResyncVolumeRequest) ProtoMessage() {}

func (x *ResyncVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResyncVolumeRequest.ProtoReflect.Descriptor instead.
func (*ResyncVolumeRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{8}
}

func (x *ResyncVolumeRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

func (x *ResyncVolumeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *ResyncVolumeRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ResyncVolumeRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *ResyncVolumeRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

func (x *ResyncVolumeRequest) GetReplicationSource() *ReplicationSource {
	if x != nil {
		return x.ReplicationSource
	}
	return nil
}

// ResyncVolumeResponse holds the information to send when
// volume is successfully resynced.
type ResyncVolumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates that the volume is ready to use.
	// The default value is false.
	// This field is REQUIRED.
	Ready         bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResyncVolumeResponse) Reset() {
	*x = ResyncVolumeResponse{}
	mi := &file_replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResyncVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResyncVolumeResponse) ProtoMessage() {}

func (x *ResyncVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResyncVolumeResponse.ProtoReflect.Descriptor instead.
func (*ResyncVolumeResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{9}
}

func (x *ResyncVolumeResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// getVolumeReplicationInfoRequest holds the required information to get the Volume replication info.
type GetVolumeReplicationInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for the replication.
	// This field is OPTIONAL.
	// This field MUST contain enough information, together with volume_id,
	// to uniquely identify this specific replication
	// vs all other replications supported by this plugin.
	ReplicationId string `protobuf:"bytes,2,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	// Secrets required by the plugin to complete the request.
	SecretName      string `protobuf:"bytes,3,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,4,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	// If specified, this field will contain volume or volume group id
	// for replication.
	ReplicationSource *ReplicationSource `protobuf:"bytes,5,opt,name=replication_source,json=replicationSource,proto3" json:"replication_source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetVolumeReplicationInfoRequest) Reset() {
	*x = GetVolumeReplicationInfoRequest{}
	mi := &file_replication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeReplicationInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeReplicationInfoRequest) ProtoMessage() {}

func (x *GetVolumeReplicationInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeReplicationInfoRequest.ProtoReflect.Descriptor instead.
func (*GetVolumeReplicationInfoRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{10}
}

func (x *GetVolumeReplicationInfoRequest) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

func (x *GetVolumeReplicationInfoRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *GetVolumeReplicationInfoRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

func (x *GetVolumeReplicationInfoRequest) GetReplicationSource() *ReplicationSource {
	if x != nil {
		return x.ReplicationSource
	}
	return nil
}

// GetVolumeReplicationInfoResponse holds the information to send the
// volume replication info.
type GetVolumeReplicationInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Holds the last sync time.
	// This field is REQUIRED.
	LastSyncTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	// Holds the last sync duration.
	// last_sync_duration represents the time taken
	// to execute the last sync operation.
	// This field is OPTIONAL.
	LastSyncDuration *durationpb.Duration `protobuf:"bytes,2,opt,name=last_sync_duration,json=lastSyncDuration,proto3" json:"last_sync_duration,omitempty"`
	// Holds the last sync bytes.
	// Represents number of bytes transferred
	// with the last synchronization.
	// A value of 0 is equal to an unspecified field value.
	// The value of this field MUST NOT be negative.
	// This field is OPTIONAL.
	LastSyncBytes int64 `protobuf:"varint,3,opt,name=last_sync_bytes,json=lastSyncBytes,proto3" json:"last_sync_bytes,omitempty"`
	// Represents the current replication status as reported by
	// the backend storage system.
	// This field is REQUIRED.
	Status GetVolumeReplicationInfoResponse_Status `protobuf:"varint,4,opt,name=status,proto3,enum=proto.GetVolumeReplicationInfoResponse_Status" json:"status,omitempty"`
	// Contains a human readable message that describes the current
	// state of replication
	// This field is OPTIONAL.
	StatusMessage string `protobuf:"bytes,5,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeReplicationInfoResponse) Reset() {
	*x = GetVolumeReplicationInfoResponse{}
	mi := &file_replication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeReplicationInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeReplicationInfoResponse) ProtoMessage() {}

func (x *GetVolumeReplicationInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeReplicationInfoResponse.ProtoReflect.Descriptor instead.
func (*GetVolumeReplicationInfoResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{11}
}

func (x *GetVolumeReplicationInfoResponse) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

func (x *GetVolumeReplicationInfoResponse) GetLastSyncDuration() *durationpb.Duration {
	if x != nil {
		return x.LastSyncDuration
	}
	return nil
}

func (x *GetVolumeReplicationInfoResponse) GetLastSyncBytes() int64 {
	if x != nil {
		return x.LastSyncBytes
	}
	return 0
}

func (x *GetVolumeReplicationInfoResponse) GetStatus() GetVolumeReplicationInfoResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetVolumeReplicationInfoResponse_UNKNOWN
}

func (x *GetVolumeReplicationInfoResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

// Specifies what source the replication will be created from. One of the
// type fields MUST be specified.
type ReplicationSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*ReplicationSource_Volume
	//	*ReplicationSource_VolumeGroup
	Type          isReplicationSource_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationSource) Reset() {
	*x = ReplicationSource{}
	mi := &file_replication_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationSource) ProtoMessage() {}

func (x *ReplicationSource) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationSource.ProtoReflect.Descriptor instead.
func (*ReplicationSource) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{12}
}

func (x *ReplicationSource) GetType() isReplicationSource_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ReplicationSource) GetVolume() *ReplicationSource_VolumeSource {
	if x != nil {
		if x, ok := x.Type.(*ReplicationSource_Volume); ok {
			return x.Volume
		}
	}
	return nil
}

func (x *ReplicationSource) GetVolumeGroup() *ReplicationSource_VolumeGroupSource {
	if x != nil {
		if x, ok := x.Type.(*ReplicationSource_VolumeGroup); ok {
			return x.VolumeGroup
		}
	}
	return nil
}

type isReplicationSource_Type interface {
	isReplicationSource_Type()
}

type ReplicationSource_Volume struct {
	// Volume source type
	Volume *ReplicationSource_VolumeSource `protobuf:"bytes,1,opt,name=volume,proto3,oneof"`
}

type ReplicationSource_VolumeGroup struct {
	// Volume group source type
	VolumeGroup *ReplicationSource_VolumeGroupSource `protobuf:"bytes,2,opt,name=volume_group,json=volumeGroup,proto3,oneof"`
}

func (*ReplicationSource_Volume) isReplicationSource_Type() {}

func (*ReplicationSource_VolumeGroup) isReplicationSource_Type() {}

// VolumeSource contains the details about the volume to be replication
type ReplicationSource_VolumeSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains identity information for the existing volume.
	// This field is REQUIRED.
	VolumeId      string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationSource_VolumeSource) Reset() {
	*x = ReplicationSource_VolumeSource{}
	mi := &file_replication_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationSource_VolumeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationSource_VolumeSource) ProtoMessage() {}

func (x *ReplicationSource_VolumeSource) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationSource_VolumeSource.ProtoReflect.Descriptor instead.
func (*ReplicationSource_VolumeSource) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{12, 0}
}

func (x *ReplicationSource_VolumeSource) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

// VolumeGroupSource contains the details about
// the volume group to be replication
type ReplicationSource_VolumeGroupSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains identity information for the existing volume group.
	// This field is REQUIRED.
	VolumeGroupId string `protobuf:"bytes,1,opt,name=volume_group_id,json=volumeGroupId,proto3" json:"volume_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationSource_VolumeGroupSource) Reset() {
	*x = ReplicationSource_VolumeGroupSource{}
	mi := &file_replication_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationSource_VolumeGroupSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationSource_VolumeGroupSource) ProtoMessage() {}

func (x *ReplicationSource_VolumeGroupSource) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationSource_VolumeGroupSource.ProtoReflect.Descriptor instead.
func (*ReplicationSource_VolumeGroupSource) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{12, 1}
}

func (x *ReplicationSource_VolumeGroupSource) GetVolumeGroupId() string {
	if x != nil {
		return x.VolumeGroupId
	}
	return ""
}

var File_replication_proto protoreflect.FileDescriptor

const file_replication_proto_rawDesc = "" +
	"\n" +
	"\x11replication.proto\x12\x05proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x02\n" +
	"\x1eEnableVolumeReplicationRequest\x12%\n" +
	"\x0ereplication_id\x18\x02 \x01(\tR\rreplicationId\x12U\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v25.proto.EnableVolumeReplicationRequest.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vsecret_name\x18\x04 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x05 \x01(\tR\x0fsecretNamespace\x12G\n" +
	"\x12replication_source\x18\x06 \x01(\v2\x18.proto.ReplicationSourceR\x11replicationSource\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02\"!\n" +
	"\x1fEnableVolumeReplicationResponse\"\xfa\x02\n" +
	"\x1fDisableVolumeReplicationRequest\x12%\n" +
	"\x0ereplication_id\x18\x02 \x01(\tR\rreplicationId\x12V\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v26.proto.DisableVolumeReplicationRequest.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vsecret_name\x18\x04 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x05 \x01(\tR\x0fsecretNamespace\x12G\n" +
	"\x12replication_source\x18\x06 \x01(\v2\x18.proto.ReplicationSourceR\x11replicationSource\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02\"\"\n" +
	" DisableVolumeReplicationResponse\"\xfa\x02\n" +
	"\x14PromoteVolumeRequest\x12%\n" +
	"\x0ereplication_id\x18\x02 \x01(\tR\rreplicationId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12K\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2+.proto.PromoteVolumeRequest.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vsecret_name\x18\x05 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x06 \x01(\tR\x0fsecretNamespace\x12G\n" +
	"\x12replication_source\x18\a \x01(\v2\x18.proto.ReplicationSourceR\x11replicationSource\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02\"\x17\n" +
	"\x15PromoteVolumeResponse\"\xf8\x02\n" +
	"\x13DemoteVolumeRequest\x12%\n" +
	"\x0ereplication_id\x18\x02 \x01(\tR\rreplicationId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12J\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2*.proto.DemoteVolumeRequest.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vsecret_name\x18\x05 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x06 \x01(\tR\x0fsecretNamespace\x12G\n" +
	"\x12replication_source\x18\a \x01(\v2\x18.proto.ReplicationSourceR\x11replicationSource\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02\"\x16\n" +
	"\x14DemoteVolumeResponse\"\xf8\x02\n" +
	"\x13ResyncVolumeRequest\x12%\n" +
	"\x0ereplication_id\x18\x02 \x01(\tR\rreplicationId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12J\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2*.proto.ResyncVolumeRequest.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vsecret_name\x18\x05 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x06 \x01(\tR\x0fsecretNamespace\x12G\n" +
	"\x12replication_source\x18\a \x01(\v2\x18.proto.ReplicationSourceR\x11replicationSource\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02\",\n" +
	"\x14ResyncVolumeResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"\xe3\x01\n" +
	"\x1fGetVolumeReplicationInfoRequest\x12%\n" +
	"\x0ereplication_id\x18\x02 \x01(\tR\rreplicationId\x12\x1f\n" +
	"\vsecret_name\x18\x03 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x04 \x01(\tR\x0fsecretNamespace\x12G\n" +
	"\x12replication_source\x18\x05 \x01(\v2\x18.proto.ReplicationSourceR\x11replicationSourceJ\x04\b\x01\x10\x02\"\x81\x03\n" +
	" GetVolumeReplicationInfoResponse\x12@\n" +
	"\x0elast_sync_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\x12G\n" +
	"\x12last_sync_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x10lastSyncDuration\x12&\n" +
	"\x0flast_sync_bytes\x18\x03 \x01(\x03R\rlastSyncBytes\x12F\n" +
	"\x06status\x18\x04 \x01(\x0e2..proto.GetVolumeReplicationInfoResponse.StatusR\x06status\x12%\n" +
	"\x0estatus_message\x18\x05 \x01(\tR\rstatusMessage\";\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\f\n" +
	"\bDEGRADED\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"\x97\x02\n" +
	"\x11ReplicationSource\x12?\n" +
	"\x06volume\x18\x01 \x01(\v2%.proto.ReplicationSource.VolumeSourceH\x00R\x06volume\x12O\n" +
	"\fvolume_group\x18\x02 \x01(\v2*.proto.ReplicationSource.VolumeGroupSourceH\x00R\vvolumeGroup\x1a+\n" +
	"\fVolumeSource\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x1a;\n" +
	"\x11VolumeGroupSource\x12&\n" +
	"\x0fvolume_group_id\x18\x01 \x01(\tR\rvolumeGroupIdB\x06\n" +
	"\x04type2\xbb\x04\n" +
	"\vReplication\x12j\n" +
	"\x17EnableVolumeReplication\x12%.proto.EnableVolumeReplicationRequest\x1a&.proto.EnableVolumeReplicationResponse\"\x00\x12m\n" +
	"\x18DisableVolumeReplication\x12&.proto.DisableVolumeReplicationRequest\x1a'.proto.DisableVolumeReplicationResponse\"\x00\x12L\n" +
	"\rPromoteVolume\x12\x1b.proto.PromoteVolumeRequest\x1a\x1c.proto.PromoteVolumeResponse\"\x00\x12I\n" +
	"\fDemoteVolume\x12\x1a.proto.DemoteVolumeRequest\x1a\x1b.proto.DemoteVolumeResponse\"\x00\x12I\n" +
	"\fResyncVolume\x12\x1a.proto.ResyncVolumeRequest\x1a\x1b.proto.ResyncVolumeResponse\"\x00\x12m\n" +
	"\x18GetVolumeReplicationInfo\x12&.proto.GetVolumeReplicationInfoRequest\x1a'.proto.GetVolumeReplicationInfoResponse\"\x00B<Z:github.com/csi-addons/kubernetes-csi-addons/internal/protob\x06proto3"

var (
	file_replication_proto_rawDescOnce sync.Once
	file_replication_proto_rawDescData []byte
)

func file_replication_proto_rawDescGZIP() []byte {
	file_replication_proto_rawDescOnce.Do(func() {
		file_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_proto_rawDesc), len(file_replication_proto_rawDesc)))
	})
	return file_replication_proto_rawDescData
}

var file_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_replication_proto_goTypes = []any{
	(GetVolumeReplicationInfoResponse_Status)(0), // 0: proto.GetVolumeReplicationInfoResponse.Status
	(*EnableVolumeReplicationRequest)(nil),       // 1: proto.EnableVolumeReplicationRequest
	(*EnableVolumeReplicationResponse)(nil),      // 2: proto.EnableVolumeReplicationResponse
	(*DisableVolumeReplicationRequest)(nil),      // 3: proto.DisableVolumeReplicationRequest
	(*DisableVolumeReplicationResponse)(nil),     // 4: proto.DisableVolumeReplicationResponse
	(*PromoteVolumeRequest)(nil),                 // 5: proto.PromoteVolumeRequest
	(*PromoteVolumeResponse)(nil),                // 6: proto.PromoteVolumeResponse
	(*DemoteVolumeRequest)(nil),                  // 7: proto.DemoteVolumeRequest
	(*DemoteVolumeResponse)(nil),                 // 8: proto.DemoteVolumeResponse
	(*ResyncVolumeRequest)(nil),                  // 9: proto.ResyncVolumeRequest
	(*ResyncVolumeResponse)(nil),                 // 10: proto.ResyncVolumeResponse
	(*GetVolumeReplicationInfoRequest)(nil),      // 11: proto.GetVolumeReplicationInfoRequest
	(*GetVolumeReplicationInfoResponse)(nil),     // 12: proto.GetVolumeReplicationInfoResponse
	(*ReplicationSource)(nil),                    // 13: proto.ReplicationSource
	nil,                                          // 14: proto.EnableVolumeReplicationRequest.ParametersEntry
	nil,                                          // 15: proto.DisableVolumeReplicationRequest.ParametersEntry
	nil,                                          // 16: proto.PromoteVolumeRequest.ParametersEntry
	nil,                                          // 17: proto.DemoteVolumeRequest.ParametersEntry
	nil,                                          // 18: proto.ResyncVolumeRequest.ParametersEntry
	(*ReplicationSource_VolumeSource)(nil),       // 19: proto.ReplicationSource.VolumeSource
	(*ReplicationSource_VolumeGroupSource)(nil),  // 20: proto.ReplicationSource.VolumeGroupSource
	(*timestamppb.Timestamp)(nil),                // 21: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                  // 22: google.protobuf.Duration
}
var file_replication_proto_depIdxs = []int32{
	14, // 0: proto.EnableVolumeReplicationRequest.parameters:type_name -> proto.EnableVolumeReplicationRequest.ParametersEntry
	13, // 1: proto.EnableVolumeReplicationRequest.replication_source:type_name -> proto.ReplicationSource
	15, // 2: proto.DisableVolumeReplicationRequest.parameters:type_name -> proto.DisableVolumeReplicationRequest.ParametersEntry
	13, // 3: proto.DisableVolumeReplicationRequest.replication_source:type_name -> proto.ReplicationSource
	16, // 4: proto.PromoteVolumeRequest.parameters:type_name -> proto.PromoteVolumeRequest.ParametersEntry
	13, // 5: proto.PromoteVolumeRequest.replication_source:type_name -> proto.ReplicationSource
	17, // 6: proto.DemoteVolumeRequest.parameters:type_name -> proto.DemoteVolumeRequest.ParametersEntry
	13, // 7: proto.DemoteVolumeRequest.replication_source:type_name -> proto.ReplicationSource
	18, // 8: proto.ResyncVolumeRequest.parameters:type_name -> proto.ResyncVolumeRequest.ParametersEntry
	13, // 9: proto.ResyncVolumeRequest.replication_source:type_name -> proto.ReplicationSource
	13, // 10: proto.GetVolumeReplicationInfoRequest.replication_source:type_name -> proto.ReplicationSource
	21, // 11: proto.GetVolumeReplicationInfoResponse.last_sync_time:type_name -> google.protobuf.Timestamp
	22, // 12: proto.GetVolumeReplicationInfoResponse.last_sync_duration:type_name -> google.protobuf.Duration
	0,  // 13: proto.GetVolumeReplicationInfoResponse.status:type_name -> proto.GetVolumeReplicationInfoResponse.Status
	19, // 14: proto.ReplicationSource.volume:type_name -> proto.ReplicationSource.VolumeSource
	20, // 15: proto.ReplicationSource.volume_group:type_name -> proto.ReplicationSource.VolumeGroupSource
	1,  // 16: proto.Replication.EnableVolumeReplication:input_type -> proto.EnableVolumeReplicationRequest
	3,  // 17: proto.Replication.DisableVolumeReplication:input_type -> proto.DisableVolumeReplicationRequest
	5,  // 18: proto.Replication.PromoteVolume:input_type -> proto.PromoteVolumeRequest
	7,  // 19: proto.Replication.DemoteVolume:input_type -> proto.DemoteVolumeRequest
	9,  // 20: proto.Replication.ResyncVolume:input_type -> proto.ResyncVolumeRequest
	11, // 21: proto.Replication.GetVolumeReplicationInfo:input_type -> proto.GetVolumeReplicationInfoRequest
	2,  // 22: proto.Replication.EnableVolumeReplication:output_type -> proto.EnableVolumeReplicationResponse
	4,  // 23: proto.Replication.DisableVolumeReplication:output_type -> proto.DisableVolumeReplicationResponse
	6,  // 24: proto.Replication.PromoteVolume:output_type -> proto.PromoteVolumeResponse
	8,  // 25: proto.Replication.DemoteVolume:output_type -> proto.DemoteVolumeResponse
	10, // 26: proto.Replication.ResyncVolume:output_type -> proto.ResyncVolumeResponse
	12, // 27: proto.Replication.GetVolumeReplicationInfo:output_type -> proto.GetVolumeReplicationInfoResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_replication_proto_init() }
func file_replication_proto_init() {
	if File_replication_proto != nil {
		return
	}
	file_replication_proto_msgTypes[12].OneofWrappers = []any{
		(*ReplicationSource_Volume)(nil),
		(*ReplicationSource_VolumeGroup)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_proto_rawDesc), len(file_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replication_proto_goTypes,
		DependencyIndexes: file_replication_proto_depIdxs,
		EnumInfos:         file_replication_proto_enumTypes,
		MessageInfos:      file_replication_proto_msgTypes,
	}.Build()
	File_replication_proto = out.File
	file_replication_proto_goTypes = nil
	file_replication_proto_depIdxs = nil
}
