// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.0
// - protoc             v3.20.2
// source: volumegroup.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VolumeGroup_CreateVolumeGroup_FullMethodName           = "/proto.VolumeGroup/CreateVolumeGroup"
	VolumeGroup_ModifyVolumeGroupMembership_FullMethodName = "/proto.VolumeGroup/ModifyVolumeGroupMembership"
	VolumeGroup_DeleteVolumeGroup_FullMethodName           = "/proto.VolumeGroup/DeleteVolumeGroup"
	VolumeGroup_ControllerGetVolumeGroup_FullMethodName    = "/proto.VolumeGroup/ControllerGetVolumeGroup"
)

// VolumeGroupClient is the client API for VolumeGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VolumeGroup holds the RPC methods for volumeGroup and all the methods it
// exposes should be idempotent.
type VolumeGroupClient interface {
	// CreateVolumeGroup RPC call to create a volume group.
	CreateVolumeGroup(ctx context.Context, in *CreateVolumeGroupRequest, opts ...grpc.CallOption) (*CreateVolumeGroupResponse, error)
	// ModifyVolumeGroupMembership RPC call to modify a volume group.
	ModifyVolumeGroupMembership(ctx context.Context, in *ModifyVolumeGroupMembershipRequest, opts ...grpc.CallOption) (*ModifyVolumeGroupMembershipResponse, error)
	// DeleteVolumeGroup RPC call to delete a volume group.
	DeleteVolumeGroup(ctx context.Context, in *DeleteVolumeGroupRequest, opts ...grpc.CallOption) (*DeleteVolumeGroupResponse, error)
	// CreateVolumeGroup RPC call to get a volume group.
	ControllerGetVolumeGroup(ctx context.Context, in *ControllerGetVolumeGroupRequest, opts ...grpc.CallOption) (*ControllerGetVolumeGroupResponse, error)
}

type volumeGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumeGroupClient(cc grpc.ClientConnInterface) VolumeGroupClient {
	return &volumeGroupClient{cc}
}

func (c *volumeGroupClient) CreateVolumeGroup(ctx context.Context, in *CreateVolumeGroupRequest, opts ...grpc.CallOption) (*CreateVolumeGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeGroupResponse)
	err := c.cc.Invoke(ctx, VolumeGroup_CreateVolumeGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeGroupClient) ModifyVolumeGroupMembership(ctx context.Context, in *ModifyVolumeGroupMembershipRequest, opts ...grpc.CallOption) (*ModifyVolumeGroupMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyVolumeGroupMembershipResponse)
	err := c.cc.Invoke(ctx, VolumeGroup_ModifyVolumeGroupMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeGroupClient) DeleteVolumeGroup(ctx context.Context, in *DeleteVolumeGroupRequest, opts ...grpc.CallOption) (*DeleteVolumeGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVolumeGroupResponse)
	err := c.cc.Invoke(ctx, VolumeGroup_DeleteVolumeGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeGroupClient) ControllerGetVolumeGroup(ctx context.Context, in *ControllerGetVolumeGroupRequest, opts ...grpc.CallOption) (*ControllerGetVolumeGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControllerGetVolumeGroupResponse)
	err := c.cc.Invoke(ctx, VolumeGroup_ControllerGetVolumeGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeGroupServer is the server API for VolumeGroup service.
// All implementations must embed UnimplementedVolumeGroupServer
// for forward compatibility.
//
// VolumeGroup holds the RPC methods for volumeGroup and all the methods it
// exposes should be idempotent.
type VolumeGroupServer interface {
	// CreateVolumeGroup RPC call to create a volume group.
	CreateVolumeGroup(context.Context, *CreateVolumeGroupRequest) (*CreateVolumeGroupResponse, error)
	// ModifyVolumeGroupMembership RPC call to modify a volume group.
	ModifyVolumeGroupMembership(context.Context, *ModifyVolumeGroupMembershipRequest) (*ModifyVolumeGroupMembershipResponse, error)
	// DeleteVolumeGroup RPC call to delete a volume group.
	DeleteVolumeGroup(context.Context, *DeleteVolumeGroupRequest) (*DeleteVolumeGroupResponse, error)
	// CreateVolumeGroup RPC call to get a volume group.
	ControllerGetVolumeGroup(context.Context, *ControllerGetVolumeGroupRequest) (*ControllerGetVolumeGroupResponse, error)
	mustEmbedUnimplementedVolumeGroupServer()
}

// UnimplementedVolumeGroupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolumeGroupServer struct{}

func (UnimplementedVolumeGroupServer) CreateVolumeGroup(context.Context, *CreateVolumeGroupRequest) (*CreateVolumeGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolumeGroup not implemented")
}
func (UnimplementedVolumeGroupServer) ModifyVolumeGroupMembership(context.Context, *ModifyVolumeGroupMembershipRequest) (*ModifyVolumeGroupMembershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyVolumeGroupMembership not implemented")
}
func (UnimplementedVolumeGroupServer) DeleteVolumeGroup(context.Context, *DeleteVolumeGroupRequest) (*DeleteVolumeGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVolumeGroup not implemented")
}
func (UnimplementedVolumeGroupServer) ControllerGetVolumeGroup(context.Context, *ControllerGetVolumeGroupRequest) (*ControllerGetVolumeGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControllerGetVolumeGroup not implemented")
}
func (UnimplementedVolumeGroupServer) mustEmbedUnimplementedVolumeGroupServer() {}
func (UnimplementedVolumeGroupServer) testEmbeddedByValue()                     {}

// UnsafeVolumeGroupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolumeGroupServer will
// result in compilation errors.
type UnsafeVolumeGroupServer interface {
	mustEmbedUnimplementedVolumeGroupServer()
}

func RegisterVolumeGroupServer(s grpc.ServiceRegistrar, srv VolumeGroupServer) {
	// If the following call pancis, it indicates UnimplementedVolumeGroupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolumeGroup_ServiceDesc, srv)
}

func _VolumeGroup_CreateVolumeGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeGroupServer).CreateVolumeGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeGroup_CreateVolumeGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeGroupServer).CreateVolumeGroup(ctx, req.(*CreateVolumeGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeGroup_ModifyVolumeGroupMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyVolumeGroupMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeGroupServer).ModifyVolumeGroupMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeGroup_ModifyVolumeGroupMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeGroupServer).ModifyVolumeGroupMembership(ctx, req.(*ModifyVolumeGroupMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeGroup_DeleteVolumeGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeGroupServer).DeleteVolumeGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeGroup_DeleteVolumeGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeGroupServer).DeleteVolumeGroup(ctx, req.(*DeleteVolumeGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeGroup_ControllerGetVolumeGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerGetVolumeGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeGroupServer).ControllerGetVolumeGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeGroup_ControllerGetVolumeGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeGroupServer).ControllerGetVolumeGroup(ctx, req.(*ControllerGetVolumeGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VolumeGroup_ServiceDesc is the grpc.ServiceDesc for VolumeGroup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolumeGroup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VolumeGroup",
	HandlerType: (*VolumeGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVolumeGroup",
			Handler:    _VolumeGroup_CreateVolumeGroup_Handler,
		},
		{
			MethodName: "ModifyVolumeGroupMembership",
			Handler:    _VolumeGroup_ModifyVolumeGroupMembership_Handler,
		},
		{
			MethodName: "DeleteVolumeGroup",
			Handler:    _VolumeGroup_DeleteVolumeGroup_Handler,
		},
		{
			MethodName: "ControllerGetVolumeGroup",
			Handler:    _VolumeGroup_ControllerGetVolumeGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "volumegroup.proto",
}
