// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: volumegroup.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateVolumeGroupRequest holds the required information to
// create a volume group
type CreateVolumeGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// suggested name for volume group (required for idempotency)
	// This field is REQUIRED.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// params passed to the plugin to create the volume group.
	// This field is OPTIONAL.
	Parameters map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secrets required by the driver to complete the
	// create request.
	SecretName      string `protobuf:"bytes,3,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,4,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	// Specify volume_ids that will be added to the volume group.
	// This field is OPTIONAL.
	VolumeIds     []string `protobuf:"bytes,5,rep,name=volume_ids,json=volumeIds,proto3" json:"volume_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeGroupRequest) Reset() {
	*x = CreateVolumeGroupRequest{}
	mi := &file_volumegroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeGroupRequest) ProtoMessage() {}

func (x *CreateVolumeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeGroupRequest) Descriptor() ([]byte, []int) {
	return file_volumegroup_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVolumeGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeGroupRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CreateVolumeGroupRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *CreateVolumeGroupRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

func (x *CreateVolumeGroupRequest) GetVolumeIds() []string {
	if x != nil {
		return x.VolumeIds
	}
	return nil
}

// CreateVolumeGroupResponse holds the information to send when
// volumeGroup is successfully created.
type CreateVolumeGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains the identifier of the newly created volume group.
	// This field is REQUIRED.
	VolumeGroup   *VolumeGroup `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeGroupResponse) Reset() {
	*x = CreateVolumeGroupResponse{}
	mi := &file_volumegroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeGroupResponse) ProtoMessage() {}

func (x *CreateVolumeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeGroupResponse) Descriptor() ([]byte, []int) {
	return file_volumegroup_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVolumeGroupResponse) GetVolumeGroup() *VolumeGroup {
	if x != nil {
		return x.VolumeGroup
	}
	return nil
}

// VolumeGroup holds the information about a specific volume group.
type VolumeGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for this volume group, generated by the plugin.
	// This field is REQUIRED.
	VolumeGroupId string `protobuf:"bytes,1,opt,name=volume_group_id,json=volumeGroupId,proto3" json:"volume_group_id,omitempty"`
	// Opaque static properties of the volume group.
	// This field is OPTIONAL.
	VolumeGroupContext map[string]string `protobuf:"bytes,2,rep,name=volume_group_context,json=volumeGroupContext,proto3" json:"volume_group_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Underlying volume ids in this group.
	// This field is OPTIONAL.
	// To support the creation of an empty group, this list can be empty.
	// However, this field is not empty in the following cases:
	//   - Response from ControllerGetVolumeGroup if the
	//     VolumeGroup is not empty.
	//   - Response from ModifyVolumeGroupMembership if the
	//     VolumeGroup is not empty after modification.
	VolumeIds     []string `protobuf:"bytes,3,rep,name=volume_ids,json=volumeIds,proto3" json:"volume_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeGroup) Reset() {
	*x = VolumeGroup{}
	mi := &file_volumegroup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeGroup) ProtoMessage() {}

func (x *VolumeGroup) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeGroup.ProtoReflect.Descriptor instead.
func (*VolumeGroup) Descriptor() ([]byte, []int) {
	return file_volumegroup_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeGroup) GetVolumeGroupId() string {
	if x != nil {
		return x.VolumeGroupId
	}
	return ""
}

func (x *VolumeGroup) GetVolumeGroupContext() map[string]string {
	if x != nil {
		return x.VolumeGroupContext
	}
	return nil
}

func (x *VolumeGroup) GetVolumeIds() []string {
	if x != nil {
		return x.VolumeIds
	}
	return nil
}

// DeleteVolumeGroupRequest holds the required information to
// delete a volume group
type DeleteVolumeGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the volume group to be deleted.
	// This field is REQUIRED.
	VolumeGroupId string `protobuf:"bytes,1,opt,name=volume_group_id,json=volumeGroupId,proto3" json:"volume_group_id,omitempty"`
	// Secrets required by the driver to complete the
	// delete request.
	SecretName      string `protobuf:"bytes,2,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,3,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteVolumeGroupRequest) Reset() {
	*x = DeleteVolumeGroupRequest{}
	mi := &file_volumegroup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeGroupRequest) ProtoMessage() {}

func (x *DeleteVolumeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteVolumeGroupRequest) Descriptor() ([]byte, []int) {
	return file_volumegroup_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteVolumeGroupRequest) GetVolumeGroupId() string {
	if x != nil {
		return x.VolumeGroupId
	}
	return ""
}

func (x *DeleteVolumeGroupRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *DeleteVolumeGroupRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

// DeleteVolumeGroupResponse is the response to send when
// volumeGroup is successfully deleted.
type DeleteVolumeGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeGroupResponse) Reset() {
	*x = DeleteVolumeGroupResponse{}
	mi := &file_volumegroup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeGroupResponse) ProtoMessage() {}

func (x *DeleteVolumeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteVolumeGroupResponse) Descriptor() ([]byte, []int) {
	return file_volumegroup_proto_rawDescGZIP(), []int{4}
}

// ModifyVolumeGroupMembershipRequest holds the required
// information to modify a volume group
type ModifyVolumeGroupMembershipRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the volume group to be modified.
	// This field is REQUIRED.
	VolumeGroupId string `protobuf:"bytes,1,opt,name=volume_group_id,json=volumeGroupId,proto3" json:"volume_group_id,omitempty"`
	// Specify volume_ids that will be in the modified volume group.
	// This list will be compared with the volume_ids in the existing
	// group.
	// New ones will be added and missing ones will be removed.
	// If no volume_ids are provided, all existing volumes will
	// be removed from the group.
	// This field is OPTIONAL.
	VolumeIds []string `protobuf:"bytes,2,rep,name=volume_ids,json=volumeIds,proto3" json:"volume_ids,omitempty"`
	// Secrets required by the driver to complete the
	// modification request.
	SecretName      string `protobuf:"bytes,3,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,4,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	// params passed to the plugin to modify the volume group
	// or to modify the volumes in the group
	// This field is OPTIONAL.
	Parameters    map[string]string `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyVolumeGroupMembershipRequest) Reset() {
	*x = ModifyVolumeGroupMembershipRequest{}
	mi := &file_volumegroup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyVolumeGroupMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyVolumeGroupMembershipRequest) ProtoMessage() {}

func (x *ModifyVolumeGroupMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyVolumeGroupMembershipRequest.ProtoReflect.Descriptor instead.
func (*ModifyVolumeGroupMembershipRequest) Descriptor() ([]byte, []int) {
	return file_volumegroup_proto_rawDescGZIP(), []int{5}
}

func (x *ModifyVolumeGroupMembershipRequest) GetVolumeGroupId() string {
	if x != nil {
		return x.VolumeGroupId
	}
	return ""
}

func (x *ModifyVolumeGroupMembershipRequest) GetVolumeIds() []string {
	if x != nil {
		return x.VolumeIds
	}
	return nil
}

func (x *ModifyVolumeGroupMembershipRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *ModifyVolumeGroupMembershipRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

func (x *ModifyVolumeGroupMembershipRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// ModifyVolumeGroupMembershipResponse is the response to
// send when volumeGroup is successfully modified.
type ModifyVolumeGroupMembershipResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains all attributes of the modified volume group.
	// This field is REQUIRED.
	VolumeGroup   *VolumeGroup `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyVolumeGroupMembershipResponse) Reset() {
	*x = ModifyVolumeGroupMembershipResponse{}
	mi := &file_volumegroup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyVolumeGroupMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyVolumeGroupMembershipResponse) ProtoMessage() {}

func (x *ModifyVolumeGroupMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyVolumeGroupMembershipResponse.ProtoReflect.Descriptor instead.
func (*ModifyVolumeGroupMembershipResponse) Descriptor() ([]byte, []int) {
	return file_volumegroup_proto_rawDescGZIP(), []int{6}
}

func (x *ModifyVolumeGroupMembershipResponse) GetVolumeGroup() *VolumeGroup {
	if x != nil {
		return x.VolumeGroup
	}
	return nil
}

// ControllerGetVolumeGroupRequest holds the required
// information to get information on volume group
type ControllerGetVolumeGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the volume group to fetch current volume group
	// information for.
	// This field is REQUIRED.
	VolumeGroupId string `protobuf:"bytes,1,opt,name=volume_group_id,json=volumeGroupId,proto3" json:"volume_group_id,omitempty"`
	// Secrets required by the driver to complete the
	// get request.
	SecretName      string `protobuf:"bytes,2,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,3,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ControllerGetVolumeGroupRequest) Reset() {
	*x = ControllerGetVolumeGroupRequest{}
	mi := &file_volumegroup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerGetVolumeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerGetVolumeGroupRequest) ProtoMessage() {}

func (x *ControllerGetVolumeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerGetVolumeGroupRequest.ProtoReflect.Descriptor instead.
func (*ControllerGetVolumeGroupRequest) Descriptor() ([]byte, []int) {
	return file_volumegroup_proto_rawDescGZIP(), []int{7}
}

func (x *ControllerGetVolumeGroupRequest) GetVolumeGroupId() string {
	if x != nil {
		return x.VolumeGroupId
	}
	return ""
}

func (x *ControllerGetVolumeGroupRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *ControllerGetVolumeGroupRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

// ControllerGetVolumeGroupResponse is the response to
// send when volumeGroup information was successfully gathered.
type ControllerGetVolumeGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED.
	VolumeGroup   *VolumeGroup `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerGetVolumeGroupResponse) Reset() {
	*x = ControllerGetVolumeGroupResponse{}
	mi := &file_volumegroup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerGetVolumeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerGetVolumeGroupResponse) ProtoMessage() {}

func (x *ControllerGetVolumeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerGetVolumeGroupResponse.ProtoReflect.Descriptor instead.
func (*ControllerGetVolumeGroupResponse) Descriptor() ([]byte, []int) {
	return file_volumegroup_proto_rawDescGZIP(), []int{8}
}

func (x *ControllerGetVolumeGroupResponse) GetVolumeGroup() *VolumeGroup {
	if x != nil {
		return x.VolumeGroup
	}
	return nil
}

var File_volumegroup_proto protoreflect.FileDescriptor

const file_volumegroup_proto_rawDesc = "" +
	"\n" +
	"\x11volumegroup.proto\x12\x05proto\"\xa9\x02\n" +
	"\x18CreateVolumeGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12O\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2/.proto.CreateVolumeGroupRequest.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vsecret_name\x18\x03 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x04 \x01(\tR\x0fsecretNamespace\x12\x1d\n" +
	"\n" +
	"volume_ids\x18\x05 \x03(\tR\tvolumeIds\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x19CreateVolumeGroupResponse\x125\n" +
	"\fvolume_group\x18\x01 \x01(\v2\x12.proto.VolumeGroupR\vvolumeGroup\"\xf9\x01\n" +
	"\vVolumeGroup\x12&\n" +
	"\x0fvolume_group_id\x18\x01 \x01(\tR\rvolumeGroupId\x12\\\n" +
	"\x14volume_group_context\x18\x02 \x03(\v2*.proto.VolumeGroup.VolumeGroupContextEntryR\x12volumeGroupContext\x12\x1d\n" +
	"\n" +
	"volume_ids\x18\x03 \x03(\tR\tvolumeIds\x1aE\n" +
	"\x17VolumeGroupContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x18DeleteVolumeGroupRequest\x12&\n" +
	"\x0fvolume_group_id\x18\x01 \x01(\tR\rvolumeGroupId\x12\x1f\n" +
	"\vsecret_name\x18\x02 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x03 \x01(\tR\x0fsecretNamespace\"\x1b\n" +
	"\x19DeleteVolumeGroupResponse\"\xd1\x02\n" +
	"\"ModifyVolumeGroupMembershipRequest\x12&\n" +
	"\x0fvolume_group_id\x18\x01 \x01(\tR\rvolumeGroupId\x12\x1d\n" +
	"\n" +
	"volume_ids\x18\x02 \x03(\tR\tvolumeIds\x12\x1f\n" +
	"\vsecret_name\x18\x03 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x04 \x01(\tR\x0fsecretNamespace\x12Y\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v29.proto.ModifyVolumeGroupMembershipRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"#ModifyVolumeGroupMembershipResponse\x125\n" +
	"\fvolume_group\x18\x01 \x01(\v2\x12.proto.VolumeGroupR\vvolumeGroup\"\x95\x01\n" +
	"\x1fControllerGetVolumeGroupRequest\x12&\n" +
	"\x0fvolume_group_id\x18\x01 \x01(\tR\rvolumeGroupId\x12\x1f\n" +
	"\vsecret_name\x18\x02 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x03 \x01(\tR\x0fsecretNamespace\"Y\n" +
	" ControllerGetVolumeGroupResponse\x125\n" +
	"\fvolume_group\x18\x01 \x01(\v2\x12.proto.VolumeGroupR\vvolumeGroup2\xb2\x03\n" +
	"\x15VolumeGroupController\x12X\n" +
	"\x11CreateVolumeGroup\x12\x1f.proto.CreateVolumeGroupRequest\x1a .proto.CreateVolumeGroupResponse\"\x00\x12v\n" +
	"\x1bModifyVolumeGroupMembership\x12).proto.ModifyVolumeGroupMembershipRequest\x1a*.proto.ModifyVolumeGroupMembershipResponse\"\x00\x12X\n" +
	"\x11DeleteVolumeGroup\x12\x1f.proto.DeleteVolumeGroupRequest\x1a .proto.DeleteVolumeGroupResponse\"\x00\x12m\n" +
	"\x18ControllerGetVolumeGroup\x12&.proto.ControllerGetVolumeGroupRequest\x1a'.proto.ControllerGetVolumeGroupResponse\"\x00B<Z:github.com/csi-addons/kubernetes-csi-addons/internal/protob\x06proto3"

var (
	file_volumegroup_proto_rawDescOnce sync.Once
	file_volumegroup_proto_rawDescData []byte
)

func file_volumegroup_proto_rawDescGZIP() []byte {
	file_volumegroup_proto_rawDescOnce.Do(func() {
		file_volumegroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volumegroup_proto_rawDesc), len(file_volumegroup_proto_rawDesc)))
	})
	return file_volumegroup_proto_rawDescData
}

var file_volumegroup_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_volumegroup_proto_goTypes = []any{
	(*CreateVolumeGroupRequest)(nil),            // 0: proto.CreateVolumeGroupRequest
	(*CreateVolumeGroupResponse)(nil),           // 1: proto.CreateVolumeGroupResponse
	(*VolumeGroup)(nil),                         // 2: proto.VolumeGroup
	(*DeleteVolumeGroupRequest)(nil),            // 3: proto.DeleteVolumeGroupRequest
	(*DeleteVolumeGroupResponse)(nil),           // 4: proto.DeleteVolumeGroupResponse
	(*ModifyVolumeGroupMembershipRequest)(nil),  // 5: proto.ModifyVolumeGroupMembershipRequest
	(*ModifyVolumeGroupMembershipResponse)(nil), // 6: proto.ModifyVolumeGroupMembershipResponse
	(*ControllerGetVolumeGroupRequest)(nil),     // 7: proto.ControllerGetVolumeGroupRequest
	(*ControllerGetVolumeGroupResponse)(nil),    // 8: proto.ControllerGetVolumeGroupResponse
	nil,                                         // 9: proto.CreateVolumeGroupRequest.ParametersEntry
	nil,                                         // 10: proto.VolumeGroup.VolumeGroupContextEntry
	nil,                                         // 11: proto.ModifyVolumeGroupMembershipRequest.ParametersEntry
}
var file_volumegroup_proto_depIdxs = []int32{
	9,  // 0: proto.CreateVolumeGroupRequest.parameters:type_name -> proto.CreateVolumeGroupRequest.ParametersEntry
	2,  // 1: proto.CreateVolumeGroupResponse.volume_group:type_name -> proto.VolumeGroup
	10, // 2: proto.VolumeGroup.volume_group_context:type_name -> proto.VolumeGroup.VolumeGroupContextEntry
	11, // 3: proto.ModifyVolumeGroupMembershipRequest.parameters:type_name -> proto.ModifyVolumeGroupMembershipRequest.ParametersEntry
	2,  // 4: proto.ModifyVolumeGroupMembershipResponse.volume_group:type_name -> proto.VolumeGroup
	2,  // 5: proto.ControllerGetVolumeGroupResponse.volume_group:type_name -> proto.VolumeGroup
	0,  // 6: proto.VolumeGroupController.CreateVolumeGroup:input_type -> proto.CreateVolumeGroupRequest
	5,  // 7: proto.VolumeGroupController.ModifyVolumeGroupMembership:input_type -> proto.ModifyVolumeGroupMembershipRequest
	3,  // 8: proto.VolumeGroupController.DeleteVolumeGroup:input_type -> proto.DeleteVolumeGroupRequest
	7,  // 9: proto.VolumeGroupController.ControllerGetVolumeGroup:input_type -> proto.ControllerGetVolumeGroupRequest
	1,  // 10: proto.VolumeGroupController.CreateVolumeGroup:output_type -> proto.CreateVolumeGroupResponse
	6,  // 11: proto.VolumeGroupController.ModifyVolumeGroupMembership:output_type -> proto.ModifyVolumeGroupMembershipResponse
	4,  // 12: proto.VolumeGroupController.DeleteVolumeGroup:output_type -> proto.DeleteVolumeGroupResponse
	8,  // 13: proto.VolumeGroupController.ControllerGetVolumeGroup:output_type -> proto.ControllerGetVolumeGroupResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_volumegroup_proto_init() }
func file_volumegroup_proto_init() {
	if File_volumegroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volumegroup_proto_rawDesc), len(file_volumegroup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_volumegroup_proto_goTypes,
		DependencyIndexes: file_volumegroup_proto_depIdxs,
		MessageInfos:      file_volumegroup_proto_msgTypes,
	}.Build()
	File_volumegroup_proto = out.File
	file_volumegroup_proto_goTypes = nil
	file_volumegroup_proto_depIdxs = nil
}
