---
defaults:
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: smart
      strict_method: rebase

pull_request_rules:
  - name: remove outdated approvals
    conditions:
      - base~=^(main)|(release-.+)$
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: false
  - name: merge after two approvals (no API changes)
    conditions:
      - base~=^(main)|(release-.+)$
      - label!=api
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "status-success=codespell"
      - "status-success=build_controller"
      - "status-success=build_sidecar"
    actions:
      merge: {}
      dismiss_reviews: {}
      delete_head_branch: {}
  - name: API changes needs approval from a contributor and a reviewer
    conditions:
      - base~=^(main)|(release-.+)$
      - label=api
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "approved-reviews-by=@csi-addons/kubernetes-csi-addons-contributors"
      - "approved-reviews-by=@csi-addons/kubernetes-csi-addons-reviewers"
      - "status-success=codespell"
      - "status-success=build_controller"
      - "status-success=build_sidecar"
    actions:
      merge: {}
      dismiss_reviews: {}
      delete_head_branch: {}
  - name: label API change
    conditions:
      - files~=^(api/)
    actions:
      label:
        add:
          - api
  - name: label vendor change
    conditions:
      - files~=^(vendor/)
    actions:
      label:
        add:
          - vendor
  - name: request reviews from reviewers for API change
    conditions:
      - files~=^(api/)
      - -closed
      - -draft
    actions:
      request_reviews:
        users_from_teams:
          - "@csi-addons/kubernetes-csi-addons-reviewers"
  - name: request reviews from regular contributors
    conditions:
      - -closed
      - -draft
    actions:
      request_reviews:
        users_from_teams:
          - "@csi-addons/kubernetes-csi-addons-contributors"
