---
# permissions for end users to view csiaddonsnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csiaddonsnode-viewer-role
rules:
  - apiGroups:
      - csiaddons.openshift.io
    resources:
      - csiaddonsnodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - csiaddons.openshift.io
    resources:
      - csiaddonsnodes/status
    verbs:
      - get
