---
# permissions for end users to edit csiaddonsnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csiaddonsnode-editor-role
rules:
  - apiGroups:
      - csiaddons.openshift.io
    resources:
      - csiaddonsnodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - csiaddons.openshift.io
    resources:
      - csiaddonsnodes/status
    verbs:
      - get
