---
# permissions for end users to edit reclaimspacejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reclaimspacejob-editor-role
rules:
  - apiGroups:
      - csiaddons.openshift.io
    resources:
      - reclaimspacejobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - csiaddons.openshift.io
    resources:
      - reclaimspacejobs/status
    verbs:
      - get
