---
name: Login to quay.io
description: Authenticates to quay.io using repository secrets

inputs:
  username:
    description: quay.io username
    required: true
  password:
    description: quay.io password
    required: true

runs:
  using: composite
  steps:
    - name: Login to quay.io
      uses: docker/login-action@v4
      with:
        registry: quay.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
