---
name: Checkout and setup Docker Buildx
# yamllint disable rule:line-length
description: >-
  Sets up QEMU and Docker Buildx for multi-arch builds

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a  # v4.3.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e  # v4.3.0
