apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: csi-addons-controller-manager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: csi-addons
      control-plane: controller-manager
  # Ingress is not specified — deny all inbound traffic.
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
