---
name: Publish container images in quay.io
# yamllint disable rule:line-length

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  push_bundle:
    name: Push bundle container image to quay.io
    if: github.repository == 'csi-addons/kubernetes-csi-addons'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Checkout and setup Go
        uses: ./.github/actions/setup-go

      - name: Generate the bundle contents
        run: make bundle

      - name: Login to quay.io
        uses: ./.github/actions/quay-login
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push bundle container image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a  # v7.3.0
        with:
          context: .
          file: bundle.Dockerfile
          push: true
          tags: quay.io/csiaddons/k8s-bundle:latest

  push_controller:
    name: Push controller container image to quay.io
    if: github.repository == 'csi-addons/kubernetes-csi-addons'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Checkout and setup Docker Buildx
        uses: ./.github/actions/setup-buildx

      - name: Login to quay.io
        uses: ./.github/actions/quay-login
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push controller container image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a  # v7.3.0
        with:
          context: .
          file: Dockerfile
          platforms: ${{ vars.BUILD_PLATFORMS }}
          push: true
          tags: quay.io/csiaddons/k8s-controller:latest

  push_sidecar:
    name: Push sidecar container image to quay.io
    if: github.repository == 'csi-addons/kubernetes-csi-addons'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Checkout and setup Docker Buildx
        uses: ./.github/actions/setup-buildx

      - name: Login to quay.io
        uses: ./.github/actions/quay-login
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push sidecar container image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a  # v7.3.0
        with:
          context: .
          file: build/Containerfile.sidecar
          platforms: ${{ vars.BUILD_PLATFORMS }}
          push: true
          tags: quay.io/csiaddons/k8s-sidecar:latest
