---
# codespell is a GitHub Actions that runs codespell tool to catch misspell
# Reference https://github.com/codespell-project/actions-codespell
name: Codespell
# yamllint disable rule:line-length
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git,go.mod,go.sum,vendor,*.svg
          ignore_words_list: NotIn,AfterAll
          check_filenames: true
          check_hidden: true
