---
name: Test deploying controller
# yamllint disable rule:line-length
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
env:
  TAG: test

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  kind_deploy:
    name: kind_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@06c1ae10762d3b9c1644e7fe69596ae519e015a2  # v1.15.0

      - name: Checkout and setup Go
        uses: ./.github/actions/setup-go

      - name: Build container container image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc  # v7.4.0
        with:
          context: .
          file: Dockerfile
          push: false
          tags: quay.io/csiaddons/k8s-controller:${{ env.TAG }}

      - name: push image to kind cluster
        run: >
          kind
          load docker-image quay.io/csiaddons/k8s-controller:${{ env.TAG }}
          --name=chart-testing

      - name: Deploy the controller and CRDs
        run: make deploy TAG=${{ env.TAG }}

      - name: Wait for controller pod
        uses: ./.github/actions/wait-for-controller

      - name: Log the status of the failed controller pod
        if: ${{ failure() }}
        run: >
          kubectl
          -n csi-addons-system
          describe pods
          -l app.kubernetes.io/name=csi-addons
          ; false
